CREATE TABLE IF NOT EXISTS ricky_storage_locations (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  team INT UNSIGNED NOT NULL,
  parent_id INT UNSIGNED NULL,
  name VARCHAR(255) NOT NULL,
  kind VARCHAR(32) NOT NULL DEFAULT 'location',
  layout_type VARCHAR(32) NOT NULL DEFAULT 'none',
  rows_count SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  columns_count SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  position_code VARCHAR(16) NULL,
  notes TEXT NULL,
  native_storage_unit_id INT UNSIGNED NULL,
  created_by INT UNSIGNED NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modified_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_ricky_storage_locations_team (team),
  KEY idx_ricky_storage_locations_parent (parent_id),
  KEY idx_ricky_storage_locations_native (native_storage_unit_id),
  CONSTRAINT fk_ricky_storage_locations_team FOREIGN KEY (team) REFERENCES teams(id) ON DELETE CASCADE,
  CONSTRAINT fk_ricky_storage_locations_parent FOREIGN KEY (parent_id) REFERENCES ricky_storage_locations(id) ON DELETE RESTRICT,
  CONSTRAINT fk_ricky_storage_locations_user FOREIGN KEY (created_by) REFERENCES users(userid) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS ricky_storage_assignments (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  team INT UNSIGNED NOT NULL,
  location_id INT UNSIGNED NOT NULL,
  slot_code VARCHAR(16) NOT NULL,
  item_id INT UNSIGNED NOT NULL,
  qty_stored DECIMAL(10,2) UNSIGNED NOT NULL DEFAULT 1.00,
  qty_unit VARCHAR(32) NOT NULL DEFAULT 'tube',
  note TEXT NULL,
  native_storage_unit_id INT UNSIGNED NULL,
  native_container_id INT UNSIGNED NULL,
  created_by INT UNSIGNED NOT NULL,
  modified_by INT UNSIGNED NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modified_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_ricky_storage_slot (location_id, slot_code),
  KEY idx_ricky_storage_assignments_team (team),
  KEY idx_ricky_storage_assignments_item (item_id),
  KEY idx_ricky_storage_assignments_native_unit (native_storage_unit_id),
  KEY idx_ricky_storage_assignments_native_container (native_container_id),
  CONSTRAINT fk_ricky_storage_assignments_team FOREIGN KEY (team) REFERENCES teams(id) ON DELETE CASCADE,
  CONSTRAINT fk_ricky_storage_assignments_location FOREIGN KEY (location_id) REFERENCES ricky_storage_locations(id) ON DELETE RESTRICT,
  CONSTRAINT fk_ricky_storage_assignments_item FOREIGN KEY (item_id) REFERENCES items(id) ON DELETE CASCADE,
  CONSTRAINT fk_ricky_storage_assignments_created_by FOREIGN KEY (created_by) REFERENCES users(userid) ON DELETE CASCADE,
  CONSTRAINT fk_ricky_storage_assignments_modified_by FOREIGN KEY (modified_by) REFERENCES users(userid) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS ricky_storage_movements (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  team INT UNSIGNED NOT NULL,
  assignment_id INT UNSIGNED NULL,
  item_id INT UNSIGNED NULL,
  action VARCHAR(32) NOT NULL,
  from_location_id INT UNSIGNED NULL,
  from_slot_code VARCHAR(16) NULL,
  to_location_id INT UNSIGNED NULL,
  to_slot_code VARCHAR(16) NULL,
  qty_before DECIMAL(10,2) UNSIGNED NULL,
  qty_after DECIMAL(10,2) UNSIGNED NULL,
  note TEXT NULL,
  created_by INT UNSIGNED NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_ricky_storage_movements_team (team),
  KEY idx_ricky_storage_movements_item (item_id),
  CONSTRAINT fk_ricky_storage_movements_team FOREIGN KEY (team) REFERENCES teams(id) ON DELETE CASCADE,
  CONSTRAINT fk_ricky_storage_movements_assignment FOREIGN KEY (assignment_id) REFERENCES ricky_storage_assignments(id) ON DELETE SET NULL,
  CONSTRAINT fk_ricky_storage_movements_item FOREIGN KEY (item_id) REFERENCES items(id) ON DELETE SET NULL,
  CONSTRAINT fk_ricky_storage_movements_from_location FOREIGN KEY (from_location_id) REFERENCES ricky_storage_locations(id) ON DELETE SET NULL,
  CONSTRAINT fk_ricky_storage_movements_to_location FOREIGN KEY (to_location_id) REFERENCES ricky_storage_locations(id) ON DELETE SET NULL,
  CONSTRAINT fk_ricky_storage_movements_user FOREIGN KEY (created_by) REFERENCES users(userid) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
